
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-portfolio
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
      - name: portfolio-container
        image: alvarosg97/portfolio:latest
        ports:
        - containerPort: 80 
